# Generated by Django 6.0.3 on 2026-03-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=300)),
                ('package', models.CharField(choices=[('basic', 'Basic SEO'), ('standard', 'Standard SEO'), ('premium', 'Premium SEO'), ('enterprise', 'Enterprise SEO')], default='basic', max_length=20)),
                ('budget', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
